### ISSUE TITLE
可以提供preprocessing/dec.vocab数据吗？

### ISSUE THREAD

**Issue by IvyGongoogle** [yanwii/dynamic-seq2seq#1]
您好，我对您的这个项目很感兴趣，但是您可以提供`preprocessing/dec.vocab`, `preprocessing/dec.segement`， `preprocessing/enc.vocab`, `preprocessing/enc.segement`这些数据吗？

非常感谢！

**Comment by yanwii** [comment]
使用`python3 preprocessing.py` 可以生成，不过我还是上传好了。
基本语料在根目录下` question.txt answer.txt `中，可以自己构建。
