### ISSUE TITLE
训练自己的预料库出现了问题，decoder_label的维度和logits的维度不匹配

### ISSUE THREAD

**Issue by Fight-hawk** [yanwii/dynamic-seq2seq#12]
只有个别语句出现了这种问题 实在是想不明台为什么

**Comment by SimonJYang** [comment]
该项目可以作为对话系统来用吗？
例如：
input：sentence A
output：sentence B

**Comment by Fight-hawk** [comment]
已经解决了 程序中有个参数设定了question和anwser的长度最大可以相差十倍，而我的语料很多超过了这个限制，修改这个参数问题解决了

**Comment by yanwii** [comment]
https://github.com/yanwii/dynamic-seq2seq/blob/8358ffd794f9b4838a54e30266dd42eacda560e7/dynamic_seq2seq_model.py#L172
