### ISSUE TITLE
请问你在训练模型的时候训练了多久啊？

### ISSUE THREAD

**Issue by maydayxx** [yanwii/dynamic-seq2seq#13]

**Comment by renhui2018** [comment]
貌似 一条条训练很耗时

**Comment by yanwii** [comment]
可以将batch_size设大一点

**Comment by renhui2018** [comment]
batch_size 设置的30，我用了1.5W 条数据，训练了5天 loss 为 1-2 之间，训练很慢啊

**Comment by Ma-Dan** [comment]
batch_size设为100，学习率设置为0.5，10000条数据，retrain可以在6小时左右将loss降到1~2之间。主要是学习率，0.1实在太慢。还可以设置高初始学习率配合decay。另外embedding可以设置高点。
