### ISSUE TITLE
你好，请问这个是说我没有训练吗？我看里面有你之前训练的模型，我直接拿来试一试。

### ISSUE THREAD

**Issue by Lip136** [yanwii/dynamic-seq2seq#18]
Traceback (most recent call last):
  File "seq2seq.py", line 160, in <module>
    if sys.argv[1]:
IndexError: list index out of range

**Comment by yanwii** [comment]
`python2 seq2seq.py infer`

**Comment by Lip136** [comment]
感谢，明白了。。这个训练是用seq2seq.py还是prepare_dialog.py呀？就是后面跟train，有区别吗？

**Comment by yanwii** [comment]
prepare_dialog.py 只是准备小黄鸡的语料
使用`python2 seq2seq.py train`来训练模型

**Comment by Lip136** [comment]
懂了，刚刚没看到。。dialog是小黄鸡。这个如果加循环的对话，直接就可以在seq2seq.py里面改循环就可以哈？

**Comment by yanwii** [comment]
是的，我这里只是给你个例子，你可以自由的改。

**Comment by Lip136** [comment]
感谢，感谢。。
