### ISSUE TITLE
我加入一个循环输入之后，运行一直卡在这里，请问大神知道原因吗？

### ISSUE THREAD

**Issue by Lip136** [yanwii/dynamic-seq2seq#19]
('tensorflow version: ', '1.4.1')
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.482 seconds.
Prefix dict has been built succesfully.
encoder_vocab_size 1930
decoder_vocab_size 3084
2018-07-24 16:16:14.410099: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1
model/chatbot_seq2seq.ckpt--1

**Comment by Lip136** [comment]
while 1:
    keyword = raw_input()
    print seq.predict(keyword)

**Comment by yanwii** [comment]
`keyword = raw_input("> ") `
`print seq.predict(keyword)`
这个时候你需要输入一段话

**Comment by Lip136** [comment]
2333,,感谢。。对了，__EOS__这个后缀在哪儿去掉呀？
