### ISSUE TITLE
ValueError: Attempt to reuse RNNCell

### ISSUE THREAD

**Issue by yeshoujquery** [yanwii/dynamic-seq2seq#2]
出现如下错误,请帮忙解答:

ValueError: Attempt to reuse RNNCell <tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.LSTMCell object at 0x0000000007E92E48> with a different variable scope than its first use.  First use of cell was with scope 'BidirectionalEncoder/bidirectional_rnn/fw/lstm_cell', this attempt is with scope 'BidirectionalEncoder/bidirectional_rnn/bw/lstm_cell'.  Please create a new instance of the cell if you would like it to use a different set of weights.  If before you were using: MultiRNNCell([LSTMCell(...)] * num_layers), change to: MultiRNNCell([LSTMCell(...) for _ in range(num_layers)]).  If before you were using the same cell instance as both the forward and reverse cell of a bidirectional RNN, simply create two instances (one for forward, one for reverse).  In May 2017, we will start transitioning this cell's behavior to use existing stored weights, if any, when it is called with scope=None (which can lead to silent model degradation, so this error will remain until then.)

**Comment by yanwii** [comment]
建议先用tensorflow-1.0
最新的tensorflow有改动
