### ISSUE TITLE
没有过滤掉词频较小的词？

### ISSUE THREAD

**Issue by zle1992** [yanwii/dynamic-seq2seq#23]
我看preprocess.py 中没有过滤掉词频较小的词，这样数据量一大，词典就很大， 而且很多低频词，这样做seq2seq是不是不太合理？

**Comment by yanwii** [comment]
从模型的角度考虑，过大的词表肯定会对模型有一定的影响，但过滤低频词也会导致新的问题出现，在模型推断的过程中低频词会用unk代替，这样就会导致模型的结果出现偏差，所以需要其他的手段来解决这个问题。做适当权衡吧。
