### ISSUE TITLE
训练了语料库 但是感觉还是傻傻的

### ISSUE THREAD

**Issue by yeshoujquery** [yanwii/dynamic-seq2seq#3]
有什么办法让他看起来不是特别傻吗?

**Comment by yanwii** [comment]
理论上来说，语料越多效果越好，多收集一些语料吧。

**Comment by yeshoujquery** [comment]
@yanwii 现在训练的是一个ckpt(明星知识),又训练了一个语料库是(法律知识) 在一次启动的时候 怎么才能让tf 加载2个或多个 ckpt  求指教

**Comment by renhui2018** [comment]
能不能分享下你的明星知识和法律知识语料库 @yeshoujquery
