### ISSUE TITLE
你好，运行seq2seq.py，显示出No module named 'chatAction'

### ISSUE THREAD

**Issue by 13647218357** [yanwii/dynamic-seq2seq#5]

**Comment by yanwii** [comment]
已更新。

**Comment by paulcx** [comment]
Action怎么调用的，能看下原来的代码吗？现在显示什么都是类似：我是__robotname__ 。

**Comment by yanwii** [comment]
action.py 中有相应的代码。
__robotname__ 可以替换成您机器人的名字，取决于你。

**Comment by paulcx** [comment]
@yanwii 谢谢，请问在哪里还？我的理解是在infer模式下，输入地名，会直接调用action中查找相关地区的天气？目前一直显示的是类似__actWeather__的回复，这个应该是没有调用成功？

**Comment by yanwii** [comment]
问题在导入模型前是需要替换成分的。
比如：重庆的天气 -> __location__的天气，__location__会被记录下来。
这句话对应一个Action:__actWeather__。
目前显示__actWeather__，说明对应成功了，但需要调用一个Action方法，如Action.py 中的actWeather 方法，我这里是取消了的。

**Comment by paulcx** [comment]
请问是在哪里调用这个（actWeather）方法？

**Comment by yanwii** [comment]
`from action import Action`
`ac = Action()`
`ac.actWeather()`

**Comment by paulcx** [comment]
请问在哪里调用呢？

**Comment by yanwii** [comment]
稍微我会补全

**Comment by 783572361** [comment]
非常感谢

**Comment by 783572361** [comment]
您好，希望您有空把action加进去，非常感谢

**Comment by mylittlenest** [comment]
您好，现在您还没有把action加进去，希望您有空把action加进去，非常感谢

**Comment by yanwii** [comment]
这个模型已经过时，稍后我会更新到最新的api，再将action加进去

**Comment by yanwii** [comment]
已更新，具体请看[Action](https://github.com/yanwii/dynamic-seq2seq#action)
