### ISSUE TITLE
encoder_vocab_size 如何设置?

### ISSUE THREAD

**Issue by yeshoujquery** [yanwii/dynamic-seq2seq#8]
encoder_vocab_size设置多少合理?
第一次训练设置7000
但是第二次不设置7000 就会出现问题
这个该如何设置?

**Comment by yeshoujquery** [comment]
@yanwii

**Comment by yanwii** [comment]
根据你的encoder的词汇量来设置，因为模型文件中是固定大小，所以第二次更改会报错。
根据你的情况，删除模型重新训练吧。
这个值可以适当上调。

**Comment by yeshoujquery** [comment]
@yanwii  那这个代码怎么写呢? 问和答的数目不一直 如果单单是读取 设置一个值 下次训练恐怕还有存在问题 请指教

**Comment by yanwii** [comment]
比如你问题的词汇量是7000 那么encoder_vocab_size=7000
答的词汇量是6000 那么decoder_vocab_size=6000

**Comment by yeshoujquery** [comment]
@yanwii encoder_vocab_size 我就是这样设置的 获取encoder_vocabulary和decoder_vocabulary的行数分别赋值 假如第一次这些都是2818 生成了10000.ckpt 
第二次再次想训练更多数据就没办法在10000.ckpt基础上继续训练 否则就会报错

@yanwii UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,20] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.

另外问一下这个问题是?

**Comment by yanwii** [comment]
tensorflow的机制决定了模型无法修改，所以你可以适当的把数值调大一点，方便下一次能够继续训练。不然就只能重新训练了。

**Comment by yeshoujquery** [comment]
@yanwii 大概明白了 我现在第一次把样本相对控制在一个数字然后以后一直保持这个数字在训练 这样是可以的吧?

**Comment by yanwii** [comment]
这样是可以的。

**Comment by yeshoujquery** [comment]
@yanwii 如何在ckpt的基础之上继续训练呢 我第一次训练的结果是8.1M 后面我训练了很多很多都是8.1M 应该是没有涨 这样不管怎么训练都不会聪明 好奇怪啊 求解~

**Comment by yanwii** [comment]
因为这个项目是很久之前做的，可以跟进一下我的另外一个项目[基于Pytorch的中文聊天机器人](https://github.com/yanwii/seq2seq)
