### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by echo1248** [yanwii/dynamic-seq2seq#9]
if my A and Q fiie line over 10, it not good for train, tensorflow.python.framework.errors_impl.InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [20,339] and labels shape [22]

**Comment by Fight-hawk** [comment]
我也遇到了类似的问题，通过切换TensorFlow的版本，问题解决了，将安装tensorflow1.4.0

**Comment by maydayxx** [comment]
请问为什么我是使用的tf1.4也遇到了同样的错误了啊
